@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTIsImlhdCI6MTY1OTQ4NjM3OH0.9AH_XR8F3oko1S4q6kwmrzYWtRscgZWif7Ph2v4XumY

############################# useres service #############################
### create user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "firstName": "test",
    "lastName": "test",
    "password": "test2",
    "email": "test@gmail.com"
}

### login user
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "password": "test2",
    "email": "test@gmail.com"
}

### list all user
GET {{baseUrl}}/users/
Content-Type: application/json
Authorization: Bearer {{token}}

### show user info
GET {{baseUrl}}/users/12
Content-Type: application/json
Authorization: Bearer {{token}}


### update user
PUT {{baseUrl}}/users/12
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstName": "test111",
    "lastName": "test"
}

############################# products service #############################
  
### create product
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Fifa23",
    "price": "100",
    "category": "Sport"
}

### list all products
GET {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

### show product info
GET {{baseUrl}}/products/1
Content-Type: application/json
Authorization: Bearer {{token}}

### list all products by category
GET {{baseUrl}}/products?category=Sport
Content-Type: application/json
Authorization: Bearer {{token}}

### update product
PUT {{baseUrl}}/products/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Fifa23",
    "price": "100",
    "category": "Sport"
}

### delete product
DELETE {{baseUrl}}/products/1
Content-Type: application/json
Authorization: Bearer {{token}}
  


############################# orders service #############################

### create order (empty)
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "active"
}

### create order (with products)
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "active",
    "products": [
        {
            "productId": 2,
            "quantity": 2
        }
    ]
}

### show user orders
GET {{baseUrl}}/orders?status=active
Content-Type: application/json
Authorization: Bearer {{token}}

### show user recent order
GET {{baseUrl}}/orders/recent
Content-Type: application/json
Authorization: Bearer {{token}}


### update order (with products)
PUT {{baseUrl}}/orders/14
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "complete"
}