@baseUrl = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaWF0IjoxNjU5NjMxNjI3fQ.inxH2rBDacvnuo1Sc3Gnz9xmBJw3yxVVPXUd_6DJPvM

############################# useres service #############################
### create user
POST {{baseUrl}}/users
Content-Type: application/json

{
    "firstName": "Mo",
    "lastName": "Salah",
    "password": "password",
    "email": "mo.salah@test.com"
}

### login user
POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "password": "password",
    "email": "hussein.adel@test.com"
}

### list all user
GET {{baseUrl}}/users/
Content-Type: application/json
Authorization: Bearer {{token}}

### show user info
GET {{baseUrl}}/users/1
Content-Type: application/json
Authorization: Bearer {{token}}


### update user
PUT {{baseUrl}}/users/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "firstName": "Hussein",
    "lastName": "Adel"
}


############################# products service #############################
  
### create product
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Coffee Machine",
    "price": "2000",
    "category": "Electronics"
}

### list all products
GET {{baseUrl}}/products
Content-Type: application/json

### list all products by category
GET {{baseUrl}}/products?category=Sport
Content-Type: application/json

### show product info
GET {{baseUrl}}/products/1
Content-Type: application/json

### update product
PUT {{baseUrl}}/products/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Fifa22",
    "price": "170",
    "category": "Sport"
}

### delete product
DELETE {{baseUrl}}/products/1
Content-Type: application/json
Authorization: Bearer {{token}}
  

############################# orders service #############################

### create order (empty)
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "active"
}

### create order (with products)
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "active",
    "products": [
        {
            "productId": 2,
            "quantity": 2
        }
    ]
}

### show user orders
GET {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{token}}

### show user active orders
GET {{baseUrl}}/orders?status=active
Content-Type: application/json
Authorization: Bearer {{token}}

### show user complete orders
GET {{baseUrl}}/orders?status=complete
Content-Type: application/json
Authorization: Bearer {{token}}

### show user recent order
GET {{baseUrl}}/orders/recent
Content-Type: application/json
Authorization: Bearer {{token}}

### update order change status
PUT {{baseUrl}}/orders/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "complete"
}

### update order (with products)
PUT {{baseUrl}}/orders/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "status": "active",
    "products": [
        {
            "productId": 2,
            "quantity": 2
        }
    ]
}